services:
  api:
    build:
      context: ./server
    env_file:
      - ./server/.env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sailraceiq
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
#     driver: local
#     networks:
#       - sailraceiq-net
# networks:
#   sailraceiq-net: {}  # Define the network