services:
  app:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    # command: uvicorn server.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ENV: ${ENV}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      CORS_ORIGINS: ${CORS_ORIGINS}

  db:
    image: postgres:15
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: