services:
  api:
    build:
      context: ./server
    env_file:
      - ./server/.env.dev
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    command: uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload --app-dir src
