services:
  app:
    build:
      context: ./
      dockerfile: dockerfile-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: "uvicorn server.main:app --host 0.0.0.0 --port 8000 --app-dir src"


  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  atlas:
    build:
      context: ./
      dockerfile: dockerfile-atlas
    env_file:
      - .env
    depends_on:
      - db
    command: /bin/sh -c "until pg_isready -h db -p 5432; do echo 'Waiting for DB'; sleep 2; done; atlas migrate apply --url \"$DATABASE_URL\"?sslmode=disable"


volumes:
  postgres-data: