services:
  app:
    build:
      context: ./
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: "uvicorn server.main:app --host 0.0.0.0 --port 8000 --app-dir src"


  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: