FROM debian:bookworm-slim

WORKDIR /db

ADD migrations/ ./migrations
COPY atlas.hcl schema.pg.hcl ./

RUN apt-get update && \
    apt-get install -y curl postgresql-client && \
    curl -sSf https://atlasgo.sh | sh

ENV PATH="/root/.atlas/bin:$PATH"
